### ISSUE TITLE
Installation of Tekla Structures Convertor - Error

### ISSUE THREAD

**Issue by bau-tech** [specklesystems/speckle-sharp#1052]
1.) Installing from Speckle Manager is not working, getting Message: failed to install
2.) If I do a manual installation, after starting Tekla Structures 2020/2021 I get the following Message from Tekla:

Laden des Plug-ins fehlgeschlagen
Assembly:C:\TeklaStructures\2020.0\\nt\bin\plugins\Speckle2TeklaStructures\arm64\libHarfBuzzSharp.dll
Fehler:
NotSupportedException: Die angegebene Methode wird nicht unterstützt.
![ErrorLoadingPlugin](https://user-images.githubusercontent.com/67436425/155307935-40db4f09-312b-40a1-a1e9-64fdd2aee6dc.PNG)

Laden des Plug-ins fehlgeschlagen
Assembly:C:\TeklaStructures\2020.0\\nt\bin\plugins\Speckle2TeklaStructures\arm64\libSkiaSharp.dll
Fehler:
NotSupportedException: Die angegebene Methode wird nicht unterstützt.

**Comment by Reynold-Chan** [comment]
The good thing is the second error is not an error. Those dependencies will not work.

**Comment by Reynold-Chan** [comment]
Sorry by any chance do you have Tekla2021, we might have found a bug with Tekla2020 that might lead to more tricky support. If you do, can you test it on Tekla2021. 

Was able to reproduce your error in 2020

**Comment by bau-tech** [comment]
I tried now with TS2021 and I get the same error at startup witch I ignore.
One click on the Plugin SpeckleConnector gives this erro
![SpeckleConnectorTS2021](https://user-images.githubusercontent.com/67436425/155355542-9a47b11c-ed5c-493f-99b3-12154420aa9d.PNG)
Double Click on the Connector and I get this:
![SpeckleConnectorTS2021_double_click](https://user-images.githubusercontent.com/67436425/155355732-dd4899ee-ae2c-41e1-bb2f-352de47ca08f.PNG)


Please instruct how to debug this issue so that you get the right information for fixing.

**Comment by Reynold-Chan** [comment]
So the mainform popping up is also expected behavior. However I am not sure what went wrong here. Can you try a clean install and delete everything.  I am also not sure why the Speckle Logo here has turned into RODBJKD. 

I was not able to reproduce your error for this one on other  people's comuter. seems like a language package problem that weirdly popped up. Also if you have mac instead of windows, let me know.  

https://speckle-releases.netlify.app/

![image](https://user-images.githubusercontent.com/29717150/155367503-933c1d61-81c9-436d-a8e1-34ae9ea85e4f.png)

click the toggle button to install 2.3.4 and not 2.4.0 

Thanks for testing everything here. Appreciate it a lot :)

**Comment by PavelNedviga** [comment]
Hi! 
The same message appears in Speckle for Tekla 2021 whel opening the Tekla model. Launching of speckle in model causes critical error with closing Tekla. What reason can cause the problem?

**Comment by Reynold-Chan** [comment]
can you give screenshots ? the error message when opening if it's the one above. It's not a worry. We will fix it soon but it shouldn't destroy your tekla . 

What do you mean critical error  ? please give screenshot ?
