### ISSUE TITLE
PolyLine.GetPoints() returns 4 points for a rectangular, closed polyline

### ISSUE THREAD

**Issue by tlmnrnhrdt** [specklesystems/speckle-sharp#1200]
Revit `ConvertOpening` expects `PolyLine.GetPoints()` to return 5 points:

```
if (poly == null || poly.GetPoints().Count != 5)
            throw new SpeckleException($"Curve outline for wall opening must be a rectangle-shaped polyline.");
```

Either this needs to become

`if (poly == null || poly.GetPoints().Count != 4 || !poly.closed))`

or `PolyLine.GetPoints()` has to return 5 points if polyline is closed.

Or is the approach here that for some reason start and end point of a rectangle are _not_ unique?

Happy to create a PR for that :)

**Comment by tlmnrnhrdt** [comment]
I am raising this because Polyline explicitly says _not_ to store five points for a rectangle..

**Comment by d3ssy** [comment]
Revit API has a IsRectBoundary property on Opening, checking that the boundary is in fact an actual rectangle, rather than just a 4 sided closed curve.

In Speckle the test below is only checking that the polyline has 5 points and assuming that means it's rectangular. But it could be trapezoidal? Is the intention to convert rectangular and non-rectangular openings differently?

```C#
if (poly == null || poly.GetPoints().Count != 5)
            throw new SpeckleException($"Curve outline for wall opening must be a rectangle-shaped polyline.");
```

**Comment by tlmnrnhrdt** [comment]
> Revit API has a IsRectBoundary property on Opening, checking that the boundary is in fact an actual rectangle, rather than just a 4 sided closed curve.
> 
> In Speckle the test below is only checking that the polyline has 5 points and assuming that means it's rectangular. But it could be trapezoidal? Is the intention to handle the conversion of rectangular and non-rectangular openings differently?
> 
> ```cs
> if (poly == null || poly.GetPoints().Count != 5)
>             throw new SpeckleException($"Curve outline for wall opening must be a rectangle-shaped polyline.");
> ```

If I understand correctly that type of opening is always rectangular in Revit.
That said, when I create a rectangular polyline myself it has by definition only 4 points:

```
namespace Objects.Geometry
{
  public class Polyline : Base, ICurve, IHasArea, IHasBoundingBox, IConvertible, ITransformable
  {
    [DetachProperty]
    [Chunkable(31250)]
    public List<double> value { get; set; } = new List<double>();

    /// <summary>
    /// If true, do not add the last point to the value list. Polyline first and last points should be unique.
    /// </summary>
    public bool closed { get; set; }
```

So either the check in the Revit converter or the definition of how polylines are stored is wrong..

**Comment by tlmnrnhrdt** [comment]
.. or I am misunderstanding something ;)

**Comment by d3ssy** [comment]
If that opening type should be limited exclusively to rectangular boundaries, then it could be a good idea to enforce that in RevitWallOpening constructor with two points (rectangle corners) to define the opening...

https://github.com/specklesystems/speckle-sharp/blob/2ff4833ffaf51d63b2f96bdd1739a2ecc7099334/Objects/Objects/BuiltElements/Opening.cs#L50

**Comment by AlanRynne** [comment]
Hi @tlmnrnhrdt  and @d3ssy!

You are right! And if I hadn't made a gif of it working (commits included) I would have been doubting myself if it ever worked 😓 

Not sure what happened there but I did some tests yesterday and that condition needs changing. Since we're releasing a new version i'm going to push it in myself so this change get's included.

As for the `RevitWallOpening` constructor, I agree it is currently "too generic" and should be more specific. I'm working on a fix for the upcoming release too. This is already tracked here https://github.com/specklesystems/speckle-sharp/issues/1199 :)
