### ISSUE TITLE
Revit: allow disabling support for linked files

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#1239]
There might be IP/ownership concerns if sending liked files all the time automatically

**Comment by DuncanLithgow** [comment]
Yes, but that issue is for the user to solve. If I have received a model from a project partner it is my responsibility to treat the received data respectfully.

Settings to make it easier to avoid problems would be good - a simple checkbox to select which links should be included in an export should be fine. No exporting from links by default might be the best approach.

**Comment by teocomi** [comment]
Thanks @DuncanLithgow we might run a poll on the forum to see what most people would the default behavior for this one be ;)

**Comment by teocomi** [comment]
Support has been added in the settings!
