### ISSUE TITLE
Core: Implement New Invite Strategy

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#1434]
2 Core tests are failing due to a miss-alignment with `speckle-server`: https://app.circleci.com/pipelines/github/specklesystems/speckle-sharp/6736/workflows/73f23ab4-72df-46ff-9767-5e084f965972/jobs/19064

Change was introduced here https://github.com/specklesystems/speckle-server/commit/da9224a069cace19087952fcfa610c84726eb854

**Comment by teocomi** [comment]
Updated the issue title as there are a few more things that should be done here:
- [ ] update the existing `StreamInviteCreate` method in core to invite users by Id as well and not just email
- [ ] update DUI correspondingly to say `Invite` instead of `Add` etc
- [ ] create `StreamInviteCreate` tests (if possible?)
- [ ] update `StreamUpdatePermission` tests  (if possible?)
- [ ] optional: show pending invites in DUI (we probably need a new endpoint for that)

**Comment by AlanRynne** [comment]
I'm assuming this was left open by mistake, as all linked PRs are merged already, so I'm closing it
