### ISSUE TITLE
💌 Share streams with users who don't have a speckle account yet

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#152]
### Expected vs. Actual Behaviour

Currently when you add collaborators to a stream on the DesktopUi, you can only search for existing users on the stream. There should be an option to share with an email address if the person they want to share a stream with does not have a speckle account yet. This should then send an email to this new person inviting them to create a speckle account.

This requires a lot of legwork on server as mentioned in specklesystems/speckle-server#62

**Comment by didimitrie** [comment]
The `invites:create` scope required for this is currently private; meaning that only the frontend application can use the necessary endpoints. 

Unless we want to open a custom link to the frontend, e.g. `/streams/12345?inviteUser=true`, that would open the send invite dialog for that stream, I would close this issue.

**Comment by didimitrie** [comment]
Okay, since this was easy to add, it's now implemented in the frontend. Next step is desktop ui implementation (and maybe gh/dyn connectors via a right click menu option?). 

What needs to be done is simply open up the stream page with an extra query parameter, specifically `invite=true`. 

A full example would be: `http://localhost:3000/streams/a75ab4f10f?invite=true`. Over to y'all; i'll re-assign this to the .net guardians.
