### ISSUE TITLE
external(autocad): improve dimension conversions

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#1583]
**This is a master issue for the Autocad / Civil3d Dimension conversion improvement task.** 

The goal is to improve current dimension conversion support in Autocad <-> Autocad workflows, with the following sequence of tasks for each time of Autocad `Dimension`:

- Create a test file for the `Dimension` sub type, to cover all reasonable and common cases of the dimension. For example, an ordinate dimension test file should contain various forms of both horizontal and vertical ordinate dimensions with different styles applied.
- Send the test file to Speckle from Autocad, and then receive it. If the received version is not identical to the sent version, fix the conversion.

**Build from the most current release branch: release/2.8**

------------------------------------------------------------------------------------------
**Current conversion state**

Conversion results from the Autocad Standard test file (provided)
![image](https://user-images.githubusercontent.com/16748799/188334798-19d0a1cf-ccff-4966-a921-0385ac438dcd.png)

Known issues:
- Radial and Diametric dimensions have incorrect center point and leader styling
- Anglular dimension value is incorrect
- Rotated dimension text point is incorrect

------------------------------------------------------------------------------------------
**Progress and estimated timeline: 1-3 hours per dimension**
As progress is made on each dimension, please comment on this issue with:
(1) a link to the created test file for review
(2) the results of sending and receiving the initial test file in autocad
(3) any conversion issues observed and a rough estimate for how long it would take to fix
(4) check each box below as it is completed

`AlignedDimension`: 
- [ ] Create test file
- [ ] Test and fix test file conversion issues

`RotatedDimension`:
- [ ] Create test file
- [ ] Test and fix test file conversion issues

`OrdinateDimension`
- [ ] Create test file
- [ ] Test and fix test file conversion issues

`RadialDimension`
- [ ] Create test file
- [ ] Test and fix test file conversion issues

`DiametricDimension`
- [ ] Create test file
- [ ] Test and fix test file conversion issues

`ArcDimension`
- [ ] Create test file
- [ ] Test and fix test file conversion issues

`LineAngularDimension2`
- [ ] Create test file
- [ ] Test and fix test file conversion issues

`Point3AngularDimension`
- [ ] Create test file
- [ ] Test and fix test file conversion issues

**Comment by clairekuang** [comment]
`SampleDimension`
Test file link: [ ]
Initial results: [ ]

---
Issues:
- [ ] Sample issue (eg text point is incorrect)

Estimated time to fix:

**Comment by motoyaa** [comment]
`AlignedDimension`

- [x] Create test file
- [x] Test and fix test file conversion issues

(1)  dwg has been posted in discord
(2)  screen shot has been posted in discord
(3)  No conversion issues found


`RotatedDimension`

- [x] Create test file
- [x] Test and fix test file conversion issues

(1)  dwg has been posted in discord
(2)  screen shot has been posted in discord
(3)  There is a text location issue in RotatedDimension (Text has moved to another location but not received correctly).


`OrdinateDimension`

- [ ] Create test file
- [ ] Test and fix test file conversion issues

`RadialDimension`

- [ ] Create test file
- [ ] Test and fix test file conversion issues


`DiametricDimension`

- [ ] Create test file
- [ ] Test and fix test file conversion issues

`ArcDimension`

- [ ] Create test file
- [ ] Test and fix test file conversion issues

`LineAngularDimension2`

- [ ] Create test file
- [ ] Test and fix test file conversion issues


`Point3AngularDimension`

- [ ] Create test file
- [ ] Test and fix test file conversion issues

**Comment by bimgeek** [comment]
## Description

Dimensions sent from Autocad can be received back but with a catch, they are not the old dimensions anymore 🙂. Take a look at the screenshots below.

## Expected Behaviour

Receiving dimensions back as we sent them.

## Steps to reproduce

1. Open Autocad test file.
2. Select dimensions to Speckle.
3. Open a new drawing and receive what you just sent.
4. Compare the two drawings.

## Streams/Commits Used

[https://latest.speckle.dev/streams/3ed8357f29/commits/46905429f6](https://latest.speckle.dev/streams/3ed8357f29/commits/46905429f6)

## Files Used

Autocad Test File

[https://drive.google.com/open?id=1-Ci9fX0xfOgtMy0phTIlqzIZeqMV72pM&authuser=bilal%40speckle.systems&usp=drive_fs](https://drive.google.com/open?id=1-Ci9fX0xfOgtMy0phTIlqzIZeqMV72pM&authuser=bilal%40speckle.systems&usp=drive_fs)

## Screenshots

Sent:

![image](https://user-images.githubusercontent.com/51519350/203508350-d74fecd6-00e6-4341-82fd-6b33b378b2da.png)

Received:

![image](https://user-images.githubusercontent.com/51519350/203508401-55873c14-ed2d-4d58-99e5-f46ec3deed05.png)

## Related Issues

#1625

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
