### ISSUE TITLE
bug(dynamo): Object Reference not set to an instance of an object

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1682]
## Description

I sent couple blocks from Autocad. When i try to receive the commit containing these blocks, I get the following error👇:

> Warning: Object reference not set to an instance of an object.
>

![image](https://user-images.githubusercontent.com/51519350/194822028-db3a1f2d-1cc0-4409-bcd5-caf2a15b720d.png)

## Expected Behaviour

Receive blocks in Dynamo without getting any error.

## Steps to reproduce

1. Open the `Four Chairs.dwg` file attached. (Go to Step 3 to skip sending from Autocad)
2. Select the blocks in the drawing and send them to Speckleverse.
3. Open Dynamo and copy URL of the commit containing the blocks sent. (Or you can use [[this commit](https://speckle.xyz/streams/f0532359ac/commits/698d2f6c1c)](https://speckle.xyz/streams/f0532359ac/commits/698d2f6c1c))
4. Use `Receive` node to receive that commit.

## Streams/Commits Used

[https://speckle.xyz/streams/f0532359ac/commits/698d2f6c1c](https://speckle.xyz/streams/f0532359ac/commits/698d2f6c1c)

## Files Used

[https://drive.google.com/open?id=14ZLGGnACoeE0sZLpnL0izUqrrZzLqDCv&authuser=bilal%40speckle.systems&usp=drive_fs](https://drive.google.com/open?id=14ZLGGnACoeE0sZLpnL0izUqrrZzLqDCv&authuser=bilal%40speckle.systems&usp=drive_fs)

**Comment by AlanRynne** [comment]
I cannot reproduce your exact error. The one I get is the same as in #1683 
<img width="504" alt="Screenshot 2022-10-17 at 13 57 30" src="https://user-images.githubusercontent.com/2316535/196171263-a771ef89-a87c-46e9-8b04-bbd68f92d174.png">

**Comment by bimgeek** [comment]
Hey Alan,

I got this error on 2.8 release when I couldn't make it work on 2.9 beta release.

**Comment by AlanRynne** [comment]
Related to #1683 

We've determined that this may be an issue with `Transform` conventions that has remained undetected until now, or an issue with the `GetInsertionPlane()` function, which is the one used when calling `Plane.insertionPoint`.

Since this is a new edge-case that needs to be covered, not a newly introduced bug (@bimgeek correct me if I'm wrong 🙌🏼), @clairekuang and I have decided to push this fix to `2.10`, as it is not a blocker for the `2.9` release.

_Originally posted by @AlanRynne in https://github.com/specklesystems/speckle-sharp/issues/1683#issuecomment-1286925279_
