### ISSUE TITLE
bug(dynamo): Axes of this plane are parallel!

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1683]
## Description

I sent couple blocks from Autocad. When i try to receive the commit containing these blocks, I get the following error👇:

> Warning: Could not create Plane! The desired axes of this plane are parallel!
>

![image](https://user-images.githubusercontent.com/51519350/194825222-34955b6b-c5dd-436c-897e-c8560f4dfd36.png)

## Expected Behaviour

Receive blocks in Dynamo without getting any error.

## Steps to reproduce

1. Open the `HEB-Lighting Blocks.dwg` file attached. (Go to Step 3 to skip sending from Autocad)
2. Select the layer containing lighting elements in the drawing and send them to Speckleverse.
3. Open Dynamo and copy URL of the commit containing the blocks sent. (Or you can use [[this commit](https://speckle.xyz/streams/f0532359ac/commits/ede29d6a0b)](https://speckle.xyz/streams/f0532359ac/commits/ede29d6a0b))
4. Use `Receive` node to receive that commit.

## Streams/Commits Used

[https://speckle.xyz/streams/f0532359ac/commits/ede29d6a0b](https://speckle.xyz/streams/f0532359ac/commits/ede29d6a0b)

## Files Used

[https://drive.google.com/open?id=14aWOSTxtv8hszwwKZ2lWiyr3HpKuCrxJ&authuser=bilal%40speckle.systems&usp=drive_fs](https://drive.google.com/open?id=14aWOSTxtv8hszwwKZ2lWiyr3HpKuCrxJ&authuser=bilal%40speckle.systems&usp=drive_fs)

**Comment by AlanRynne** [comment]
This may actually be an ACAD issue, but it may also be possible to "fix" it in Dynamo in some way. If you receive those blocks in Rhino... do they convert correctly?
<img width="534" alt="Screenshot 2022-10-17 at 14 02 19" src="https://user-images.githubusercontent.com/2316535/196172281-ca06737b-9e7e-45a6-a36e-0b195bb64312.png">

**Comment by AlanRynne** [comment]
After a quick chat with Claire, we're going to split this up into separate issues:

- This issue, which we'll try to fix by trying to correct the invalid vectors. Either by making them unit length or by deriving it from the other 2.
- An Acad specific issue, where we'll try to get Acad to not spit out such "funky" planes. This may not be easily fixable due to ACAD API limitations... which is why we'll implement a fix on Dynamo

**Comment by AlanRynne** [comment]
As a side thought @bimgeek, could you confirm this ACAD blocks are converted correctly in Rhino/Sketchup?

Just looking for confirmation that these blocks are not inherently broken due to the plane coords

**Comment by bimgeek** [comment]
#### Rhino ⚠
I don't get any error but no geometry is generated either.
![image](https://user-images.githubusercontent.com/51519350/196203852-6d172e2d-17cf-4cfb-94ae-68facc72bfa3.png)

#### Grasshopper ✅
Successfully received and i can access its insertion plane.
![image](https://user-images.githubusercontent.com/51519350/196203661-4bf5e15c-b261-4bea-a6d6-4d8bab20ead1.png)

#### Sketchup ⚠
No errors, no geometry.
![image](https://user-images.githubusercontent.com/51519350/196205681-be1be1e7-031f-43db-9686-959b9472cca4.png)

**Comment by AlanRynne** [comment]
We've determined that this may be an issue with `Transform` conventions that has remained undetected until now, or an issue with the `GetInsertionPlane()` function, which is the one used when calling `Plane.insertionPoint`.

Since this is a new edge-case that needs to be covered, not a newly introduced bug (@bimgeek correct me if I'm wrong 🙌🏼), @clairekuang and I have decided to push this fix to `2.10`, as it is not a blocker for the `2.9` release.
