### ISSUE TITLE
DUI: Activity content does not change when branch is changed

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#1719]
Changing the selected branch on a Stream in DUI does not update the content's of the Activity panel.

It's a bit confusing because it will continue to reflect the wrong activity even after saving and reloading the view.

![2022-10-14 11 08 15](https://user-images.githubusercontent.com/2316535/195809204-a2398f13-817e-4a35-9f10-7c46687e0409.gif)

**Comment by AlanRynne** [comment]
🤔 interesting, that's a bit of a bummer... since different branches do have different "activity". I was expecting it to reflect the latest event on the selected branch, could this be something we filter in DUI instead?

**Comment by teocomi** [comment]
It's possible, but filtering on the client side could lead to unexpected results because of pagination.
Let's say there are 10 activity events on branch A and then 1 on branch B, if the limit is set to 10, you'll never see that event on branch B... Sounds like a better addition to https://github.com/specklesystems/speckle-server/issues/616 instead.

**Comment by AlanRynne** [comment]
hmm Ok got it! I've marked it as an `enhancement/papercut` instead, and I'll remove it form our 2.9 release as the behaviour is the expected one.
