### ISSUE TITLE
Speckle don’t send all data point cloud from lidar mobile

### ISSUE THREAD

**Issue by chuongmep** [specklesystems/speckle-sharp#1816]
## Prerequisites

Need insert file point cloud to revit model

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## Describe the bug

Bug when push point cloud from Revit Model, something missing point 
https://speckle.community/t/speckle-dont-send-all-dada-point-cloud-from-lidar-mobile/4034/6

We are missing it here: 
https://github.com/specklesystems/speckle-sharp/blob/b56aa04e789652ecb7d4ba944ca7ad613e898254/Objects/Converters/ConverterRevit/ConverterRevitShared/Partial%20Classes/ConvertGeometry.cs#L105-L112

## To Reproduce

1. Go to Revit
2. Insert file point cloud
3. push to speckle

## Expected behavior

All point cloud will be show in speckle

## Screenshots

![image](https://user-images.githubusercontent.com/31106432/200213660-17d75492-4022-4bb1-88c0-fe8b3bc54ce0.png)

**Comment by bimgeek** [comment]
Related to this [thread ](https://speckle.community/t/speckle-dont-send-all-data-point-cloud-from-lidar-mobile/4034)reported by @chuongmep

## Description

User links a point cloud file to Revit. He then selects this file and sends it to a stream. However, points below a certain Z value do not appear in the 3D viewer. You can confirm this by checking the stream below.

This can be reproduced. I changed the location of the linked point cloud file and rotated it 90 and 180 degrees. Nothing changed. It only sends the upper half of all the points (needs confirmation).

Also, this is not a viewer issue. When the same commit is received in Rhino, only points in the viewer show up.

## Expected Behaviour

Send all points to Speckleverse.

## Steps to reproduce

1. Open a new blank project in Revit
2. `Link` attached point cloud file
3. Enable Speckle connector and check `Send Linked Models` option under `Advanced Settings`
4. Select the linked point cloud file and `Send` to Speckleverse.
5. Open newly made commit and examine it.

## Streams/Commits Used

[https://latest.speckle.dev/streams/32953abf86](https://latest.speckle.dev/streams/32953abf86)

## Files Used

### Point Cloud File

[https://drive.google.com/drive/folders/14r8YRzcOSq3FtICNu77kuDIUMSc--n8a?usp=share_link](https://drive.google.com/drive/folders/14r8YRzcOSq3FtICNu77kuDIUMSc--n8a?usp=share_link)

## Screenshots

Point cloud file viewed in Revit
![image](https://user-images.githubusercontent.com/51519350/200231351-e76fb00f-59ab-48e3-8d81-e0441670150c.png)
Send to Speckle
![image](https://user-images.githubusercontent.com/51519350/200231372-dba25a2b-ff5b-4eea-bb3f-da64944c1f03.png)
Same commit received in Rhino👇
![image](https://user-images.githubusercontent.com/51519350/200231399-cb056a74-ee16-4330-93e9-87a01275dde7.png)

**Comment by teocomi** [comment]
Other relevant conversation here:
- (private PM): https://speckle.community/t/youre-a-new-user-of-the-year/3967/15
