### ISSUE TITLE
bug(rhino): Rhino creates a new layer for each receive

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1836]
## Description

For each model version received from Speckleverse, a new layer structure is created in Rhino. Let's say a version of a Revit model is received. Rhino creates the layer structure for this version. Later, the Revit model was updated and now a new version will be received. When the new version is received, a layer structure is created **again** next to the previous one. In other words, **when 10 versions are received, users end up with 10 separate layer structures.** This is an undesired and unexpected problem from a user's pov.

## Expected Behaviour

Create a layer for a model and track versions through this single layer structure.

## Steps to reproduce

1. Open Rhino and enable Speckle connector.
2. Add below model by URL.
3. Receive first version. Rhino will create the layers.
4. Receive the second version. Rhino will create another layer structure.

> If you don't want to follow these steps, you can watch the video recording below.
> 

## Streams/Commits Used

[https://latest.speckle.dev/streams/1fedfb65da/branches/main](https://latest.speckle.dev/streams/1fedfb65da/branches/main)

## Screenshots

https://user-images.githubusercontent.com/51519350/201307939-1d9b1441-b1c4-4f6b-96ad-473f2aac7966.mp4

![image](https://user-images.githubusercontent.com/51519350/201307924-4b722515-72ad-4224-9cf7-ba9864456117.png)

**Comment by clairekuang** [comment]
So this was originally by design and isn't a bug, but with the new update recieve mode, objects should now be placed on the layer of the object they are replacing. 

In order to fully capture the behavior you're requesting, we'll need to open a new feature to add a `layer setting` to rhino (and autocad) to allow users to select if they want to create a top level commit layer or not, for both update and create receive mode. This is because update mode currently still creates a new `commit`::`layer` layer for the object if it is not replacing any object in the current document.

**Comment by teocomi** [comment]
How about creating the top-level commit object only if the receive mode is `Create`?
Would save us from adding an additional setting...

**Comment by clairekuang** [comment]
Yes I can do that as well, if @bimgeek is ok with no top layer commit on `Update` mode I'll go ahead and remove it

**Comment by bimgeek** [comment]
yep, works for me.
