### ISSUE TITLE
Standard Code To collaborate

### ISSUE THREAD

**Issue by chuongmep** [specklesystems/speckle-sharp#1848]
Hi team, 
I want to collaborate but I see sometime we setting code standard use both  `Lowercase letters` and `Capitalize first letter` for attributes. I want question whether we need improve that or not, or have any reason to use it ? 

Like that : 
https://github.com/specklesystems/speckle-sharp/blob/84a40937d947b35f56d24f51d3fdf944b819a038/Core/Core/Credentials/Account.cs#L36-L41
Some time like that : 
https://github.com/specklesystems/speckle-sharp/blob/57bb41aeb3ff7dd56d36dc0ebdd7caad0e372d57/Core/Core/Kits/Attributes.cs#L21-L29
So what code should I follow in your source code?
Thank you !

**Comment by teocomi** [comment]
Hi @chuongmep ,

Any class representing objects that come from our API uses the Lowercase convention (eg anything in Objects or under Accounts) so that it more closely matches its js/json counterparts; anything else uses the normal Capitalized convention.

Looking forward to your contributions and feel free to also use the forum when asking questions :)

**Comment by chuongmep** [comment]
Thanks @teocomi , will do it .
