### ISSUE TITLE
bug(dynamo): Warning: Could not convert Plane(id=) to Dynamo.

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sharp#1949]
## Description

I am planning to record a tutorial about converting CAD blocks to Revit families. When I send the blocks from the CAD file I created and receive it in Dynamo, I encounter the following error:

> Warning: Could not convert Plane(id=) to Dynamo.
Could not create Plane! one or more of the desired axes of this plane have zero length!
> 

The value of “insertionPlane” is null in most of the blocks.

## Expected Behaviour

Getting the insertionPlane of all blocks, successfully.

## Steps to reproduce

1. Open attached file.
2. Select furniture blocks and send it to Speckleverse. (or use the attached branch)
3. Open Dynamo and try to receive the sent file.
4. You’ll get an error.

## Streams/Commits Used

[https://latest.speckle.dev/streams/4b0d719855/branches/cad blocks](https://latest.speckle.dev/streams/4b0d719855/branches/cad%20blocks)

## Files Used

[https://drive.google.com/open?id=1xd8Z9J2TmpgZlL0Ekmyrjxw93iXBzOno&authuser=bilal%40speckle.systems&usp=drive_fs](https://drive.google.com/open?id=1xd8Z9J2TmpgZlL0Ekmyrjxw93iXBzOno&authuser=bilal%40speckle.systems&usp=drive_fs)

## Connector Version

Autocad - 2.10.0-rc5

Dynamo - 2.10.0-rc5

Revit - 2.10.0-rc5

## Screenshots

![image](https://user-images.githubusercontent.com/51519350/204717969-fa780ae5-3080-4375-a347-73d5998e7a71.png)

**Comment by AlanRynne** [comment]
I double checked all the data in Grasshopper and the `GetInsertionPlane()` function that computes the block insertion plane has some kind of bug. Rhino is fine with wrongly created planes (planes with axises with 0 length for example) but Dynamo is **not ok** with this.

The failing blocks end up having a plane X Axis that has `0,0,0` coords.
<img width="801" alt="Screenshot 2022-11-30 at 08 46 26" src="https://user-images.githubusercontent.com/2316535/204738415-b1bd9454-f66d-407c-a4ac-7a8dc98a73fa.png">

Since Rhino also exposes the insertion plane, attempted to compute it using Grasshopper directly, and this returned a different Plane that the one `GetInsertionPlane` returns. The rotation of it is different, and my guess would be the Rhino method **does compute the correct plane**, and ours has an extra rotation to it.

- The plane from Speckle
<img width="888" alt="Screenshot 2022-11-30 at 08 56 33" src="https://user-images.githubusercontent.com/2316535/204739279-dab2cdbe-903c-4fde-9864-874b60455c8c.png">

- the Plane computed from Rhino (transforming an XY Plane using the provided transform)
<img width="869" alt="Screenshot 2022-11-30 at 08 56 26" src="https://user-images.githubusercontent.com/2316535/204739310-e16b9acb-7210-4963-a154-884ece6f9b0d.png">

- Both planes overlapping
<img width="890" alt="Screenshot 2022-11-30 at 08 56 41" src="https://user-images.githubusercontent.com/2316535/204739241-6848c871-4ed0-4a8c-b96a-b8235df33a60.png">

So my take is that this is not a Dynamo thing, but rather some bug on our **Transform** logic. I have no idea how this actually works in the background so I'm assigning this to @JR-Morgan and @clairekuang

**Comment by AlanRynne** [comment]
Related to #1683
