### ISSUE TITLE
papercut(autocad/civil): null applicationId causes exception preventing conversion

### ISSUE THREAD

**Issue by dtnaughton** [specklesystems/speckle-sharp#2383]
Issue encountered receiving data into AutoCAD 22 in 'update' receive mode. We've seen an edge case where an object's applicationId was null, which caused an exception on [checking for an existing object in the model](https://github.com/specklesystems/speckle-sharp/blob/main/ConnectorAutocadCivil/ConnectorAutocadCivil/Utils.cs#L536). This exception is caught on receiving entire commit obj, so no other objects receive successfully.

I think more ideal behaviour could be either of the following:
- Add a null or empty check on applicationId. If null, return empty list of existing objects and allow the object to be created as new.
- Catch the exception in a lower level of the conversion so just the specific object conversion fails ([somewhere here](https://github.com/specklesystems/speckle-sharp/blob/main/ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs#L403)), and other objects will convert/receive successfully.

These are just my initial thoughts, so happy to continue discussion!

**Comment by clairekuang** [comment]
Taking a look at this now - we are checking for null `applicationId`s [here](https://github.com/specklesystems/speckle-sharp/blob/6f5b88c24f3c3be8d591ef77e7b5b053014b020e/ConnectorAutocadCivil/ConnectorAutocadCivil/Utils.cs#L501) but in your case the string may have been empty rather than null. Pushing a fix for that soon, the behavior will be as described in your first bullet point ✌️
