### ISSUE TITLE
Clicking on the feedback toast after sending data leads to an Error web page

### ISSUE THREAD

**Issue by Gaschitz** [specklesystems/speckle-sharp#2707]
## What package are you referring to?

Rhino, SketchUp, maybe all?

## Describe the bug

Send data to https://latest.speckle.systems/
Get the feedback toast
![image](https://github.com/specklesystems/speckle-sharp/assets/57147683/5b18dce2-524e-4d62-80ee-e4bb17f7023f)
Click on it
Error message
![image](https://github.com/specklesystems/speckle-sharp/assets/57147683/90535506-b304-459e-a10d-9014957d4fd5)

+1 info > The file upload succeeded, the model is reachable from the dashboard. Only the shortcut link between the host app and the server is broken

### Desktop (please complete the following information):

- OS: WIN11
- Browser: Chrome

**Comment by AlanRynne** [comment]
As far as I'm aware, we only support frontend2 links in the UI for our connectors at the moment, so many of these redirect buttons may not take you to the right place.
I've verified that it works in `latest.speckle.dev` which uses the old frontend.

**Comment by AlanRynne** [comment]
Interestingly I get a different error (the one I would have expected) since the URL is invalid for the new frontend:

This is where that pop-up takes me https://latest.speckle.systems/streams/4e51c4025f/commits/bfb98ba1e7
Which still follows the old url pattern. We have no way to tell if a server uses the old or the new right now, so we'd have to chat about this with Dim

<img width="1180" alt="Screenshot 2023-06-28 at 13 06 29" src="https://github.com/specklesystems/speckle-sharp/assets/2316535/aa9e5d66-bfb0-4277-96a5-45fd8facf0ff">

**Comment by Gaschitz** [comment]
Thank you!

**Comment by teocomi** [comment]
There is an option under the profile icon to use FE2 links - not very intuitive but it's what we have :)
