### ISSUE TITLE
GH: issues with clusters and custom speckle objects

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#293]
See conversation on the forum: https://discourse.speckle.works/t/speckle-custom-object-in-cluster/1210

**Comment by AlanRynne** [comment]
So... I investigated a bit on this and it turns out that our `async` components do not like being inside clusters. 

If it is what I suspect, it is due to the fact that _Grasshopper Clusters_ only like to run **_one_** solution, while our `async` component runs several solutions to enable the async behaviour.

In the gif, you can see that the output object of the cluster doesn't get updated on a "once per change" basis. It takes 2 or 3 changes for the solution to expire the latest data. Most of the time it displays one or two iterations behind the current one.

![2021-03-17 13 08 40](https://user-images.githubusercontent.com/2316535/111465147-02c47780-8722-11eb-8b04-19f434ba4e49.gif)

Not sure what kind of control we could have on the execution order from within a cluster, I haven't found any documentation about that.

I would propose either:

- If it can be done, polish the AsyncComponent to play nice with clusters (not sure if this is even possible)
- Discourage the use of clusters. Tbh, I never use them and every time I've seen a cluster in someone's file it was there to hide a horrible GH spaghetti mess 😅 
- Once the `Rhino.Compute` non-async nodes are released, we could argue they should just use those.

**Comment by AlanRynne** [comment]
This should be fixed once we merge in the changes discussed in #539
