### ISSUE TITLE
Bug: Reading in `speckle_type` from Server

### ISSUE THREAD

**Issue by sanchez** [specklesystems/speckle-sharp#3066]
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

Speckle CSharp SDKs

## Describe the bug

Hi, I have some data I am pulling down from Speckle and I have noticed that the `speckle_type` field does not match up between the server and local. I am pulling the data through the Speckle CSharp library and have followed these instructions: https://speckle.guide/dev/dotnet.html 

It looks as though `speckle_type` is being set as either `Base` or `Speckle.Core.Models.Collection`. I have attached some screenshots below of local vs web.

I have a feeling it's because `__type` is marked as [SchemaIgnore] but `speckle_type` is a readonly property, therefore when serializing the object is converted to Base and then `speckle_type` fetches the from the new Base object instead of the serializer being able to set the correct type. However I am not too familiar with the codebase to know where to look to check.

## To Reproduce

Follow the dotnet tutorial and download object data.

## Expected behavior

`speckle_type` should match the field saved in the server

## Screenshots

![image](https://github.com/specklesystems/speckle-sharp/assets/5264697/c869fde4-b345-4692-b00e-dfbe06aea8ca)
![image](https://github.com/specklesystems/speckle-sharp/assets/5264697/c1774149-2225-458b-ad90-c01a9e77397d)

## System Info

If applicable, please fill in the below details - they help a lot!

Windows 10, running dotnet 6 console, using Speckle.Core 2.16.0 and Speckle.Objects 2.16.0. Speckle Manager is not installed on my machine.

Cheers,
Daniel

**Comment by sanchez** [comment]
Okay, so I found a solution as a work around. If I add `new Objects.Geometry.Line();` before I fetch from the server then the objects are serialized to their proper type and `speckle_type` looks correct. The only problem I see, what happens if I use a custom type but haven't registered the a deserialization type on the receive and instead just need a quick query or something. `speckle_type` field would still be incorrect?

**Comment by AlanRynne** [comment]
Hey @sanchez!

We're aware of this behaviour, and it's something we have no control over.

The way the dotnet runtime works (as far as we've gathered), is that it won't load up DLLs until the moment they're used in some part of the code. This prevent's your computer from loading up a bunch of logic that may or may not be executed.

The problem you're experiencing is due to this dotnet feature, combined with the fact that our deserialiser uses `Reflection` to cast things to its correct types, but will cast to a more generic type if the specific type does not exist (cases where you don't care about objects specifically)

This means that, when deserialising an object, the deserialiser can only know about the types that are **already loaded**. This also explains why, if you use a single class within the `Objects` dll before deserialising, you'll suddenly get all the Objects types deserialised correctly.

In all of our C# connectors, this is guaranteed to be loaded before any deserialisation operation happen by using our `KitManager`, who will fetch all kits and force-load them into the program. This is the recommended approach if you're targeting some sort of `Desktop application` and is expected to run alongside the installed speckle connectors.

For any other type of application (web apps, server backends) who do not need to co-exist with our speckle connectors, you are free to solve this issue as you see fit. A more elegant way to "load the Objects kit" without KitManager can be found in our `Automate.SDK` example repo:

```csharp
_ = typeof(ObjectsKit).Assembly; // Force objects kit to initialise
```

https://github.com/specklesystems/SpeckleAutomateDotnetExample/blob/47b0a1ab5e04c43d14b02141d5d433618ac9748f/SpeckleAutomateDotnetExample/AutomateFunction.cs#L15

As for your question regarding `Custom Types`, the deserialiser will be able to cast to those types as long as the dll holding said types has been loaded up.

You can ensure that with the above trick too ;)

Hope this helps!

**Comment by sanchez** [comment]
Thanks for the detailed response @AlanRynne. I guess some situations I am thinking of, is say we have some tool produced in JavaScript which pushes some custom objects, but then we want to do some basic querying in CSharp for some reason.

On the CSharp side we don't want to have to type out all the definitions, we might only want to do something simple like get a specific property from an object if the Speckle type starts with a specific namespace. Super simplified but the idea is sort of there I believe. 

I would say that even if the object is deserialized to Base, the speckle_type property should still be the original type that's fetched from the server

**Comment by AlanRynne** [comment]
I see, sadly this is not how our SDKs were designed. Speckle assumes that if you want to send an object across 2 different programming languages, you need the object representation on both sides.

Additionally, `speckle_type` value is computed on our SDK objects based on the actual type it is and it's inheritance. It is not something you can override, the `speckle_type` of a given object will always tell you what type it is "at that given moment"
This is because `speckle_type` is used as the JSON discriminator when deserialising, so you can't just set it to anything (well, you can, but it'll revert to Base upon deserialisation if the type you specified was not found)

If you don't want to type out the definitions in C#, just send objects with speckle_type `Base` from your application and use another property of your choosing to discriminate against (`customType`?)

As long as your application follows your own rules you should be good to go. That being said... you will be better off just typing them in both languages on the long run.

**Comment by sanchez** [comment]
No worries, thanks for the info. Since I guess this is by design and not necessarily a bug, I am happy to close this out.
