### ISSUE TITLE
Pass GraphQL Errors From Client Operations

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sharp#32]
### Expected vs. Actual Behavior

At the moment, [GraphQL Client Operations](https://github.com/specklesystems/Core/blob/master/Core/Api/Client.GraphqlClientOperations.cs) all return standard string errors (eg "Could not create stream"). It would be more helpful if the specific GraphQL errors could be passed on in the message so you don't have to dig all the way into core to find out what the actual error is.

### Reproduction Steps & System Config (win, osx, web, etc.)

Make any bad GraphQL request using `Client.GraphqlClientOperations`.

### Proposed Solution (if any)

Pass the actual GraphQL errors into the `GraphQLException`.

**Comment by didimitrie** [comment]
Yep, the extra doesn't seem to be carried over in the exception here:
https://github.com/specklesystems/Core/blob/25c08e7e3fd3232b1d20b466a7c8f5330d59c4bb/Core/Logging/Log.cs#L67-L76

I also feel like - this might be a bikeshed design moment - it would be a bit more natural to invert the ops a bit. What do i mean by this:
- in code, just `throw new SpeckleException( ... )s` - which can be constructed from GQL errors, like above, or from normal exceptions
- in the constructors, do a `Log.Capture( ... )`

This would change this:

https://github.com/specklesystems/Core/blob/25c08e7e3fd3232b1d20b466a7c8f5330d59c4bb/Core/Api/Client.GraphqlClientOperations.cs#L40-L49

to 

```cs

 public async Task<User> UserGet()
    {
      try
      {
        var request = new GraphQLRequest
        {
          Query = etc
        };

        var res = await GQLClient.SendMutationAsync<UserData>(request);

        if (res.Errors != null)
          throw new SpeckleException( res.errors );

        return res.Data.user;
      }
      catch (Exception e)
      {
         throw new SpeckleException( e );
      }
    }
```

**Comment by izzylys** [comment]
I like this idea! Feels more natural to be throwing a `SpeckleException` rather than faffing with capturing and throwing. imho easier to use and cleaner to read ✨

**Comment by teocomi** [comment]
Okay, this should be fixed with: https://github.com/specklesystems/Core/pull/65/commits/ee3edc92153c0768e4f9f7a34c87c80011887d5e#diff-76acbbd665fda0e26440acdb0d57074b4183fe02631e41b17bc9d7aebd2d83ebR52

It's now returning the first gql error. Initially I had standardized on predefined error messages to be able to group these exceptions in Sentry. Feel free to close @didimitrie

**Comment by didimitrie** [comment]
The democratic consensus above is that we'll clean that up so we can do `throw new SpeckleException( ... )` instead of `Log.CaptureAndThrow()`, so it stays open :D

The SpeckleException class will have multiple constructors covering any cases we might want to wrap around. 

TBH, it's my fault - we discussed the `Log.CaptureAndThrow()` approach in the past when you've implemented it, but I wasn't awake enough to catch it in time...
