### ISSUE TITLE
Core: prevent misuse of detachable properties

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#356]
Current problem: let's say you have 2 base objects, one has a **typed** detached prop `[detached] wall.elements` and another has a **dynamic** detached prop `floor[@elements]`, I cannot write a function that handles them the same way
as the first would need to be called `base["elements"]` and the other `base["@elements"]`. This hampers the flexibility given by having dynamic properties as I might want to reuse the same function with both typed and dynamic objects.

Proposed solution: edit `DynamicBase.cs` so that, after being set a first time, a detachable property can be retrieved either with  `base["elements"]` or `base["@elements"]`. This also means **not** allowing having two properties with the same name that are detached and non-detached.

**Comment by didimitrie** [comment]
> Current problem: let's say you have 2 base objects, one has a typed detached prop [detached] wall.elements and another has a dynamic detached prop floor[@elements], I cannot write a function that handles them the same way
as the first would need to be called base["elements"] and the other base["@elements"]

Too late to jump in, but wouldn't refactoring the code a bit have worked out? 

Version one: 
```cs

public void floorFunction( myFloor ) {
  // ...
  handleElements( myFloor["@elements"] as List<Base>); 
}

public void wallFunction( myWall ) {
  // ...
  handleElements( myWall.elements ); 
}

public void handleElements(List<Base> elements) {
  // ...
}
```

Or version two, if you just want one function for all:  

```cs

public void handleElements( Base myBase ) {
  List<Base> elements;

  if(myBase["@elements"]) 
    elements = myBase["@elements"] as List<Base>;

  if(myBase.elements != null) 
    elements = myBase.elements; // assuming elements is a strongly typed prop of List<Base>
  
  if(elements == null) return; 

  // carry on

}


```

**Comment by teocomi** [comment]
To be fair these just seem to be workarounds to a structural problem in Core, not real solutions.
The issues I see:
- developers would have to know that they need to handle dynamic and typed properties differently when detached, this is counter-intuitive
- developers would have to know if a property is detached or not when accessing it, this is not always possible especially when working with dynamic properties
- extra code is required to access detached properties
- if an object has the same property detached and not detached (`base["elements"]` and `base[@elements]`), then it would really hard to handle each property correctly

If we want Base to be intuitive and developer-friendly it should:
- have properties that can be accessed in the same way (whether typed or not)
- not require the end developer to know if a property is detached or not when accessing it

Dynamic properties are very powerful and will see high usage in visual programming, we need to make sure they don't add complexity down the line.

**Comment by teocomi** [comment]
As a reply to your pr comment:

> Ok thought on this more. I don't really like the backchannel extra magic, and it has the potential to add extra confusion. There's an extra layer of indirection that I feel is not needed...

Why do you think it would lead to confusion? I think it removes the confusion:

- to create a detached property you just need to use `[detachable]` or prefix it with `@`
- to access it, you just get it in any way (with or without `@`) 
- objects cannot have the same prop as detached and non-detached

Simple and intuitive IMHO :)

**Comment by didimitrie** [comment]
> To be fair these just seem to be workarounds to a structural problem in Core, not real solutions.

This is what happens **always** when you're in non-typed land, you get defensive code here and there. It's a religious war I don't want to engage in. We support this object extensibility in .net for its benefits rather than its drawbacks.

> developers would have to know that they need to handle dynamic and typed properties differently when detached, this is counter-intuitive

In what way? The problem is more for object model creators. Core handles detaching and re-attaching for you, doesn't it? 

> developers would have to know if a property is detached or not when accessing it, this is not always possible especially when working with dynamic properties

This applies only to dynamic properties; yes you need to know it's got an "@". If this is annoying to said developer, they are always allowed to make it a strongly typed prop and be done with it. 

> extra code is required to access detached properties

Not really. If it's a detached dynamic prop, you have `["@prop"]`. If it's a typed dynamic prop it's simply `var.prop`, regardless of whether it's detached or not. A cursory inspection of the serialised object would tell you its name. 

> If we want Base to be intuitive and developer-friendly it should:

> have properties that can be accessed in the same way (whether typed or not)

that's the case right now, isn't it? 

> not require the end developer to know if a property is detached or not when accessing it

Agreed. Currently, the developer needs to know the property name to access it. I'm sure this is an existential requirement though that we can't skip. 

The solution you proposed removes some confusion that personally I don't find too offensive (it literally just takes some null check on a function's arguments - hello defensive code), and adds extra confusion, as pointed by [@izzylys in the PR](https://github.com/specklesystems/speckle-sharp/pull/396#pullrequestreview-621977336):

> only thing that comes to mind is that now there is ambiguity re whether a dynamic prop is detached or not.
> eg you might think you're adding a detached prop with base["@prop"] but you're actually setting base["prop"] behind the scenes. I'm not sure if that's ok or if it could be user unfriendly behaviour. maybe if someone is actively trying to set base["@prop"] when base["prop"] exists, you should actually be removing "prop" and adding "@prop"? tho I guess issues arise here if the prop you're trying to set is actually a typed one and not a dynamic one...
> perhaps we could at least add a helper method that you can run to check if a prop is detached or not so a user can be sure they're adding a detached prop?

---

If I understand this problem correctly - the time we spent discussing this is excruciating - doesn't it actually boil down to defining the `elements` property as typed on the built elements that need it - perhaps via an interface for convenience checking (`IHasElements` or something)? 

Hence, in good faith, I don't see this as progress. **I can live with the current implementation,** but it looks like we're introducing new behaviour, that's confusing in new ways, to solve essentially an object model problem.
