### ISSUE TITLE
Rhino: surfaces with floor schema attached come out as polylines

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-sharp#366]
**Current behaviour:** 
- select a bunch of rectangular surfaces
- apply schema to them (auto)
- send 
- attempt to [view them](https://speckle.xyz/streams/df3565183f/commits/327aa0f909): they come out as polylines! 
- attempt to receive them in another rhino file: nada (layer structure is created, but nothing gets baked). 

**Expected behaviour**: get them back out as surfaces! 

Why are we actually converting rhino elements when sending, if they have a schema, to that specific schema? Can't this be done on the other end? With the current behaviour, it appears as we're "lossy-fying" the interop process in a pre-emptive way that can be avoided.

**Comment by AlanRynne** [comment]
🤔 My understanding is that we decided for it to work the same way the GH connector does with the `SchemaBuilder`, i.e. keeping the current behaviour when converting geometry to Revit, and sending built elements when specified.

I do get your point of letting Revit deal with this may have it's advantages. If I understand correctly, instead of the current behaviour, you're proposing:
- Geometry elements tagged with a `schema` should be sent as geometry types with the schema information attached as a property maybe?
- Revit conversion should check for that specific schema property and decide if it should create a `BuiltElement` or go with the default geometry conversion.

I think this is a good approach that would simplify implementing the built elements to Revit conversion on all connectors, but I'm not sure on the actual implications of this regarding the `SchemaBuilder` functionality. Whatever we do it should be consistent across platforms (to a realistic degree).

**Comment by clairekuang** [comment]
Another loose thought for approaching the schema problem: instead of having an ever-expanding collection of "BIM" classes in our objects library, create a `Schema` base class instead containing:
- Schema hash
- List of Base geometry
- List of Base primitives
- List of other Schema hashs

Users can then create and commit schemas to a stream, and pull existing schemas when they want to create instances of that schema in supported apps. The workflow for Revit would then require an extra step (having users open a revit file and send existing types as schema objs) but this could potentially make the approach more scalable and flexible for other BIM integrations
