### ISSUE TITLE
Support sending and receiving null values and properties

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#491]
How we handle `null` values varies between connectors. Our most strict implementation is GH, which directly prevents pushing null objects on a _data tree_.

Dynamo apparently has no inconvenient on sending `null` values.

The main reason behind disallowing `null` values in GH was to prevent _index shifting_ in lists of objects, as the `null` values where never serialized: `[0,null,1]` became `[0,1]` after serialization/deserialization.

There's quite a debate in the team on wether they should be allowed or not, but we should handle all cases in a consistent manner.

**Comment by OliverEGreen** [comment]
Nulls in Dynamo will often break things when they're used further down the line (depending on whether each specific node was built to handle them).

Perhaps we could give users the option?

**Comment by iltabe** [comment]
@OliverEGreen Is there any way to filter out null values in dynamo like you do in gh?

**Comment by OliverEGreen** [comment]
Hi @iltabe in Dynamo? I'd normally use List.Clean for that, with preserveIndices set to false. 
If I remember right, there's also another popular package with a List.RemoveNulls node.

**Comment by iltabe** [comment]
Then can an input with null values be cleaned after received from speckle, if needed?

**Comment by OliverEGreen** [comment]
Yeah that should work on the Dynamo side. I can't speak for Grasshopper!

**Comment by iltabe** [comment]
Great, Grasshopper can handle it the same way :)

**Comment by iltabe** [comment]
Coming back to this, I have the necessity to add empty lists or null values to objects.
If it helps, I think it's very limitative to rely on the user of having always super consistent objects. In fact, you implemented the logic of marking "Optional" a parameter.
It's totally possible to have for instance a `Beam.Screws`: a container, a list of screws... screws that could be there or not in same edge cases...

As an example, I have to cut some beams with same planes. Not all the beams though. 
I'm doing some experiments.

1. **Empty list**
Empty list is correctly assigned and converted to speckle. But when I expand the data tree, I then have inconsistent trees because the empty trees are missing. And this is dangerous because when you do data tree operation, grasshopper match the trees without looking to match the paths. 
2. **Empty nested list or dictionary**
An empty IronPython List (or dict) - assigned in the py component - is properly serialized and the conversion ToSpeckle works nicely. I get a `null` value where the list is empty which I can filter out. The conversion "ToNative" instead fails.
![image](https://user-images.githubusercontent.com/64929000/121324168-c3688a00-c910-11eb-8723-4b1a9a7c3a02.png)
3. **Null Plane**
The best workaround i found is to add a `Rhino.Geometry.Plane.Unset` where I don't have any cutplane.
It seams both `toNative` and `toSpeckle` are working... and hopefully null planes are well supported in ghp.

**Comment by didimitrie** [comment]
Closing as stale. I'm pretending to be a bot; will reopen when we have the bandwidth.

**Comment by iltabe** [comment]
:-(

**Comment by teocomi** [comment]
Hey @iltabe if you think this is still an issue let's chat next week!

**Comment by iltabe** [comment]
Hey @teocomi, more than an issue I see it as an enhancement.
Let's say we have objects with custom properties that belong to the same family (i.e walls?). I have a gut feeling that having consistent objects + null values handling (when required) it's better then break this consistency dealing with objects that don't have same attributes anymore.
What if some walls have openings and other not? `wall.Openings` will fail for some objects instead of returning an empty list.
Maybe I'm missing something tho. Let's chat!

**Comment by teocomi** [comment]
Adding this to the next sprint, we should close it once for good as it seems to be affecting various new users.
Potential solutions:
- support nulls (this will require some changes in core I believe), my preference
- do not support nulls (will require changes in most connectors so that the users can be informed and will know what to expect)

**Comment by AlanRynne** [comment]
Just pinging you @iltabe to let you know we're adding null support (finally)!

Got a PR ready for review. If you feel like testing it out I'd be happy to let you know when it makes it to the `beta` release (or feel free to build it out yourself and try it 🙂 )

**Comment by iltabe** [comment]
Good to know @AlanRynne !
I might have the chance to test it since I'm designing a digital workflow using speckle at the moment.

**Comment by teocomi** [comment]
The current implementation is incomplete we should also support `Base` objects that have `null` properties.
Re-opening and changing the title for clarity.
