### ISSUE TITLE
GH: Async get stuck in a loop

### ISSUE THREAD

**Issue by iltabe** [specklesystems/speckle-sharp#539]
Hi,

The async component get stuck when a full definition is updated from the start.
It happens almost every time, unless the component is DISABLED when the previous components are running/updating.

The most affected components: Create speckle object, Object value by key.

An old style gif made from my phone:
![ezgif-2-03dd98e136dc](https://user-images.githubusercontent.com/64929000/120465329-25b80c80-c39e-11eb-8597-bb456084c149.gif)
ahah!

I feel the async component should be used only when necessary: Sender/receiver and converters. 

Esc command won't kill the process. Maybe is worthy to add some escape-key-press-catch in the component.

**Comment by AlanRynne** [comment]
Regarding this nasty bug, had a conversation with @didimitrie today and I'm going to try investigate a possible fix.

Tbh, we're seriously thinking on reverting the Object Management nodes to inherit from `GH_Component` instead of `GH_AsyncComponent`. But I'd prefer not to do it 😓 

This would mean having a locked UI while the components do their thing, just like any other GH component.

**Comment by iltabe** [comment]
Thanks @AlanRynne.
From my user experience, the sender/receiver and the `toNative/toSpeckle` can stay Async.
All other components are very fast, and I wouldn't bother if they were like standard components.

**Comment by AlanRynne** [comment]
Thanks for your feedback. I've been trying to figure out some way to prevent this from happening other than swapping the Async nodes for normal ones, without much luck... I'll talk with the team to see if we can tackle this ASAP to get rid of that bug. We can also swap them for `TaskCapableComponent` classes if it would bring a significant performance increase.

**Comment by iltabe** [comment]
Thanks Alan.
I can live with this bug just enabling/disabling components in small batches. It's not priority for me. If the solution requires a significant change deep in the code, you can mark it p2, and have a second thought on it.

**Comment by AlanRynne** [comment]
👍🏻  we'll keep you posted then!  Meanwhile, this may ease the pain of activating/deactivating groups of components at a time (if you're not using it already!)
https://discourse.mcneel.com/t/metahopper-group-toggle/82671/2
https://www.food4rhino.com/en/app/metahopper

**Comment by AlanRynne** [comment]
Hey @iltabe, I'm going to swap the 2 most affected components to inherit from `GH_TaskCapableComponent` instead of the current `GH_AsyncComponent`. I'll surely ping you once they are done so you can test them and let us know if they do the trick :)
To prevent wrecking your entire definitions, we are planning on assigning them a new `guid`, so your files will still work with the async nodes, and you'd have to swap them for the new ones manually. Does this sound ok to you?

If we're all happy with the results, we'll swap all of them and call it a day. 👍🏻

**Comment by iltabe** [comment]
Yes, fine for me. Thanks!

**Comment by AlanRynne** [comment]
@iltabe, I just pushed 2 new TaskCapable nodes to [this branch](https://github.com/specklesystems/speckle-sharp/tree/alan/gh%2Ftask-capable-object-management). Since there are only changes to the .gha, you can just replace the `.gha` for the one I'm attaching here if you just want to test it without building the project. For now, it's just the `Create Speckle Object` and the `Object value by Key` nodes.

I'm already noticing in some of my test's that the execution is somewhat faster than our async nodes (at the cost of locking the UI until they're finished, just like any other GH node 😢 ).

[SpeckleConnectorGrasshopper.gha.zip](https://github.com/specklesystems/speckle-sharp/files/6663109/SpeckleConnectorGrasshopper.gha.zip)

As far as I've been able to test, the work exactly as their `async` counterparts, so this should solve your "async crazy loop" issue without introducing more side-effects 🤞🏻 

I'll keep going with the rest but I'm keen to hear your feedback on this!
