### ISSUE TITLE
GH: confusing behaviour of expand speckle object

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-sharp#629]
![kbtRUCBQFY](https://user-images.githubusercontent.com/7696515/126232727-73e78b84-8304-4dfb-94af-bfcf23eff38d.gif)

I suspect we can improve current logic so that when just renaming a key, we don't need to create a new one when expanding. The case can be handled if `input port count == output port count`.

**Comment by AlanRynne** [comment]
So... I'm not sure about this one. The reason it works this way is precisely to prevent the connections from shuffling, but at the same time preventing connections from disappearing without control. Since the `Expand` node has no knowledge of this `rename` process, it has to figure out if an input has been renamed by itself.

We used to rename the outputs, but this lead to cables being re-wired by grasshopper to `incorrect` outputs and random exceptions when cables where disconnected.

As far as I can tell, this renaming behaviour can only happen **one input at a time**, so the actual case would be closer to handling `input port count == output port count`**and** `only one input name has changed`.

I'll do some tests to see if this is viable.
