### ISSUE TITLE
GH load kits for current version of Rhino

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#952]
It seems that the GH connector is loading kits from `Applications.Rhino` in [multiple instances](https://github.com/specklesystems/speckle-sharp/search?q=Applications.Rhino6). Not sure if this is by design or not but we should consider automatically picking the current version of Rhino, see this issue on the forum:

https://speckle.community/t/loading-kits-in-gh/2170/5

Otherwise, we should document and explain this behavior this in the docs.

**Comment by AlanRynne** [comment]
This was "by design", or at least, it was a consequence of other decisions. Originally, we only had **a single Rhino converter** project, but we split it in 2 to support some Rhino7 specific features, but the Grasshopper connector remained as a single build for all versions.

This forced us to use `Rhino6` as the default application, since only the `Objects.Converter.Rhino6.dll` is bundled with the Grasshopper connector upon install. We could bundle the `Objects.Converter.Rhino7.dll` too, and then we'd be able to do the trick suggested in the forum with no trouble.

**Comment by AlanRynne** [comment]
Other solution would be to split the Grasshopper converter as it's own thing https://github.com/specklesystems/speckle-sharp/issues/923

**Comment by teocomi** [comment]
Moving to backlog until it becomes active again.
